name: Workflow
on:
  push:
    branches:
      - feature-Alberto-Verdugo-Ponce-Laboratorio-Final

jobs:        
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'


    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Ajusta la versión de Node.js según tus necesidades

    - name: Install dependencies
      run: npm install  # O usa `yarn install` si prefieres yarn

    - name: SonarCloud Scan
      run: |
        npm install -g sonarqube-scanner 
        sonar-scanner \
          -Dsonar.projectKey=ALBERTOVERDUGO_Laboratorio-final \
          -Dsonar.organization=albertoverdugo \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.branch.name=feature-Alberto-Verdugo-Ponce-Laboratorio-Final

#SCA -------------------------------------------

  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2      

    - name: Build
      id: build
      run: |
        #pwd
        #ls -R
        if [ -f "build.gradle" ]
        then
          echo "Utiliza build.gradle, proyecto Java"
          echo "Se habilita permiso de ejecución de archivo gradlew"
          chmod 777 gradlew
          ./gradlew build
        else
          echo "Otro tipo de proyecto"
        fi
    
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired

    - name: Upload Test result
      uses: actions/upload-artifact@v2
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: JAR
        path: ${{github.workspace}}/build/libs/LaboratorioApp.jar

# Docker Build Image ----------------------------------------

  DockerBuild:
    needs: SCA
    runs-on: self-hosted
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Download JAR
      uses: actions/download-artifact@v2
      with:
        name: JAR
        path: ${{github.workspace}}

    - name: Build Docker
      run: |
        docker build --tag albertoverdugo/Laboratoriodevsecops-test:latest .
        
